---
title: "Downscaling Trace-21ka: Summary cross-validation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Downscaling Trace-21ka: Summary cross-validation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r global_options, include=FALSE}
options(java.parameters = "-Xmx16g")
library(knitr)
opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE, cache=TRUE, eval = FALSE)
```

# Create function to extract info

```{r function_for_accuracy_metrics}
ds_validation <- function(models=ds.methods, obs=uerra.tasmin, measure.code = "bias", index.code) {
  l <- lapply(1:length(models),
                          function(i) {
                suppressMessages(
                  climate4R.value::valueMeasure(
                    obs,
                    x = get(models[i]),
                    measure.code = measure.code,
                    index.code = index.code)$Measure)
              })
  names(l) <- models
  return(l)
}
```


```{r calculate_accuracy_metrics}
ds.methods <- c("GLM.1.sp", "ANN.1.sp", "GLM.21", "ANN.21", "GLM.21.sp", "GLM.24", "GLM.24.sp", "GLM.31", "GLM.34")

value.indices <- c("Mean", "sd", "Skewness")

library(parallel)

cl <- makeCluster(detectCores())

clusterExport(cl, c("ds_validation", ds.methods, "uerra.tasmin", "value.indices"))

val.results <- parLapply(cl, value.indices,
                      function(i, j, k, l){ds_validation(models= j,
                                                         obs=k,
                                                         measure.code=l,
                                                         index.code = i)},
                      ds.methods,
                      uerra.tasmin, "bias")

stopCluster(cl)

names(val.results) <- value.indices
```


```{r map_biasses}
visualizeR::spatialPlot(val.results[[1]][[1]],
            backdrop.theme = "countries",
            main = "GLM.1.sp - bias mean")
visualizeR::spatialPlot(val.results[[1]][[2]],
            backdrop.theme = "countries",
            main = "ANN.1.sp - bias mean")
visualizeR::spatialPlot(val.results[[1]][[3]],
            backdrop.theme = "countries",
            main = "GLM.21 - bias mean")
visualizeR::spatialPlot(val.results[[1]][[4]],
            backdrop.theme = "countries",
            main = "ANN.21 - bias mean")
visualizeR::spatialPlot(val.results[[1]][[5]],
            backdrop.theme = "countries",
            main = "GLM.21.sp - bias mean")
visualizeR::spatialPlot(val.results[[1]][[6]],
            backdrop.theme = "countries",
            main = "GLM.24 - bias mean")
visualizeR::spatialPlot(val.results[[1]][[7]],
            backdrop.theme = "countries",
            main = "GLM.24.sp - bias mean")
visualizeR::spatialPlot(val.results[[1]][[8]],
            backdrop.theme = "countries",
            main = "GLM.31 - bias mean")
visualizeR::spatialPlot(val.results[[1]][[9]],
            backdrop.theme = "countries",
            main = "GLM.34 - bias mean")
```


```{r map_biasses_2, echo=FALSE}
visualizeR::spatialPlot(readd(validation)[[1]][[1]],
            backdrop.theme = "countries",
            main = "GLM.1.sp - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[2]],
            backdrop.theme = "countries",
            main = "ANN.1.sp - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[3]],
            backdrop.theme = "countries",
            main = "GLM.21 - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[4]],
            backdrop.theme = "countries",
            main = "ANN.21 - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[5]],
            backdrop.theme = "countries",
            main = "GLM.21.sp - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[6]],
            backdrop.theme = "countries",
            main = "GLM.24 - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[7]],
            backdrop.theme = "countries",
            main = "GLM.24.sp - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[8]],
            backdrop.theme = "countries",
            main = "GLM.31 - bias mean")
visualizeR::spatialPlot(readd(validation)[[1]][[9]],
            backdrop.theme = "countries",
            main = "GLM.34 - bias mean")
```


```{r plot_results}
library(reshape2)
library(ggplot2)
getGridData <- function(grid)grid$Data

test <- lapply(readd(validation), FUN=function(x)lapply(x, getGridData))

test <- melt(test)

test$mean <- ave(test$value, as.factor(test$L1), as.factor(test$L2), FUN=mean)

test$L2 <- factor(test$L2, levels = ds.methods)
test$L1 <- factor(test$L1, levels = value.indices)

ggplot(test, aes(x=L2, y=value)) + 
  geom_violin(aes(fill=mean)) +
  facet_grid(L1~., scales="free") 
```

